---
- name: Restart calibre-pod
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: calibre-pod
    state: restarted  # this works even if deploying the services for the first time
