calibre_timezone: America/Winnipeg
calibre_user_id: 1000
calibre_group_id: 1000

# https://docs.linuxserver.io/images/docker-calibre/#ports-p
calibre_http_port: 8080
calibre_ws_port: 8081
# This port is exposed from the pod and is used to connect to the desktop GUI
calibre_https_port: 8181

calibre_config_dir: /opt/calibre/config/

# A place to upload books to so they appear in the container
calibre_books_dir: /data/media/Books/

# This secret is always required
calibre_password: "SECRET-REPLACE-ME"

calibre_web_reverse_proxy: false
