calibre_timezone: America/Winnipeg
calibre_user_id: 1000
calibre_group_id: 1000

# This port is exposed from the pod and is used to connect to the desktop GUI
calibre_gui_port: 8181

calibre_config_dir: /opt/calibre/config/
calibre_web_config_dir: /opt/calibre-web/config/
calibre_web_library_dir: /opt/calibre/config/Library/

# A place to upload books to so they appear in the calibre GUI container
calibre_upload_dir: /data/media/upload/books/

# Use this variable to set the VAAPI render node for hardware video rendering
# calibre_vaapi_render_node: /dev/dri/renderD128

# This secret is always required
calibre_password: "SECRET-REPLACE-ME"

calibre_web_reverse_proxy: false
