timezone: America/Winnipeg
podman_user_id: 1010
podman_group_id: 1010

caddy:
  host_ip_is_static: false

  reverse_proxy_hosts:
    - domain_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35376164303433613631633966663735613764343433666561653365363361323131386139613936
          3663393266613938393461616136653832623763326161360a343034376636333735626561323139
          66613739626533313630623565636633386363653466633962306264653765373761666138306331
          3737616634393439630a353433623365316431613261626336383038636437383162393638383738
          33616463366532626338326533393231663063303639653332613533373439343937
      container_name: jellyfin
      port: 8096
    - domain_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33363461656230653630383235383431616636346163663063636663313430326238316537303439
          6432623330353062363562663365393264363835343837390a353066636439386561653463373432
          38636334303730316661376565626561396562316338646335643363663636636663343030636363
          6630386166323036630a353935393736626463313465376464353435633930633762613536366463
          63313838363937613534343231336436633731383837393164346363306639666139
      container_name: copyparty
      port: 3923
    - domain_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33623763623632656332633031396431313932343837396337333731643239313331323064316230
          3336613232366430646162313936353835616565633032370a376663623861376333336562656632
          32373936323734653461636138333533383433356139313137376338323132303064613863363734
          3431356133316464300a333537393137383438643933356237386538643833336533663132346132
          39323739383861333932653665333932633535363130663461626237323031346264
      container_name: starrapps  # <- Use the name of the pod, not the container in the pod
      port: 5055

calibre:
  gui_port: 8181
  web_port: 8083
  config_dir: /opt/calibre/config/
  web_config_dir: /opt/calibre-web/config/
  web_library_dir: /opt/calibre/config/MyLibrary/
  upload_dir: /data/media/upload/books/
  web_reverse_proxy: false

copyparty:
  port: 3923
  reverse_proxy: true
  config_dir: /opt/copyparty/config/
  enable_sharing: true
  share_web_path: /share/
  volumes:
    - web_path: /
      container_path: /w
      host_path: /data/

jellyfin:
  port: 8096
  reverse_proxy: true
  config_dir: /opt/jellyfin/config/
  media_dir: /data/media/

starrapps:
  media_root_dir: /data/
  media_usenet_dir: /data/usenet/
  jellyseerr_reverse_proxy: true
  jellyseerr_port: 5055
  prowlarr_config_dir: /opt/prowlarr/
  radarr_config_dir: /opt/radarr/
  sabnzbd_config_dir: /opt/sabnzbd/
  sonarr_config_dir: /opt/sonarr/
